services:
  - type: web
    name: messengerko-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: ADMIN_EMAIL
        value: admin123@admin.com
      - key: ADMIN_PASSWORD
        value: admin123
    healthCheckPath: /health
